name: Cypress Tests

on:
  workflow_dispatch: #Porque o DEV merece a magia de rodar testes sem precisar fazer aquele "pushzinho"
    inputs: 
      cli:
        description: Run by Cypress CLI
        default: npx cypress run
  push:
    branches:
      - main  #Dispara sempre que houver push na branch main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [webkit]  #Executa nos 4 navegadores

    steps: 
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}  #Roda o Cypress no navegador correspondente
