name: Cypress Tests

on:
  workflow_dispatch: #Porque o DEV merece a magia de rodar testes sem precisar fazer aquele "pushzinho" na branch
    inputs: 
      cli:
        description: Run by Cypress CLI
        default: npx cypress run
  push:
    branches:
      - main #Dispara sempre que houver push na branch main

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps: 
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install 

      - name: Run E2E Tests
        run: ${{ github.event.inputs.cli }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps: 
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install 

      - name: Run E2E Tests
        run: ${{ github.event.inputs.cli }}

  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps: 
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install 

      - name: Run E2E Tests
        run: ${{ github.event.inputs.cli }}
