name: Cypress Tests

on:
  workflow_dispatch:
    inputs: 
      cli:
        description: Run by Cypress CLI
        default: npx cypress run
  
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install 

      - name: Run E2E Tests
        run: ${{ github.event.inputs.cli }}
